name: README Repos List
on:
  schedule:
    - cron: "0 3 * * 6"

jobs:
  readme-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run readme-repos-list
        uses: koj-co/readme-repos-list@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          # query: "uses:astrochun/github-stats-pages language:yml in:file"
          query: "topic:github-stats-pages"
          max: 1000
          one-per-owner: true
